/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/recorder-ai/index" |
       "/pages/ai/deepseek" |
       "/pages/ai/index" |
       "/pages/ai-history/detail" |
       "/pages/ai-history/index" |
       "/pages/auth/index" |
       "/pages/home/index" |
       "/pages/mine/index" |
       "/pages/recorder-ai/recorder-input-auto" |
       "/pages/recorder-ai/recorder-input" |
       "/pages/test/index" |
       "/pages/recorder-ai/components/chat-video" |
       "/pages/recorder-ai/components/screensaver" |
       "/feature/pages/list-data-preview/detail" |
       "/feature/pages/list-data-preview/index" |
       "/feature/pages/sub-test/index" |
       "/feature/pages/yaml/index" |
       "/feature/pages/sub-test/component/dialog";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
