/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/home/index" |
       "/pages/ai/deepseek" |
       "/pages/ai/index" |
       "/pages/auth/index" |
       "/pages/mine/index" |
       "/pages/mine/test" |
       "/feature/pages/list-data-preview/detail" |
       "/feature/pages/list-data-preview/index" |
       "/feature/pages/recorder-ai/index" |
       "/feature/pages/recorder-ai/recorder-input" |
       "/feature/pages/sub-test/index" |
       "/feature/pages/test/index" |
       "/feature/pages/yaml/index" |
       "/feature/pages/sub-test/component/dialog" |
       "/feature/pages/test/recorder-core/index-copy" |
       "/feature/pages/test/recorder-core/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/home/index" | "/pages/mine/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
